name: irc

on: [push]

jobs:
  notification:
    runs-on: ubuntu-latest
    name: IRC notification
    steps:
      - name: Format message
        id: message
        run: |
          echo "message=$(echo ${{ github.actor }} pushed $(echo ${{ github.event.commits[0].message }} | head -n 1 | tr -d "'") ${{ github.event.commits[0].url }}" >> $GITHUB_ENV
      - name: IRC notification
        uses: Gottox/irc-message-action@v2
        with:
          channel: '#cardinal'
          nickname: github-event-bot
          message: ${{ env.message }}
